module.exports = [
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 1,
    activator: 'Character',
    eventTitle: 'Elven Cloaks',
    eventPreCondition: null,
    eventText: 'The "Elven Cloaks" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'It is a gift',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 2,
    activator: 'Character',
    eventTitle: 'Elven Rope',
    eventPreCondition: null,
    eventText: 'The "Elven Rope" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'It is a gift',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 3,
    activator: 'Character',
    eventTitle: 'Phial of Galadriel',
    eventPreCondition: null,
    eventText: 'The "Phial of Galadriel" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'It is a gift',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 4,
    activator: 'Character',
    eventTitle: 'Sméagol Helps Nice Master',
    eventPreCondition: null,
    eventText: 'The "Sméagol Helps Nice Master" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'It is a gift',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 5,
    activator: 'Character',
    eventTitle: 'Mithril Coat and Sting',
    eventPreCondition: 'Play on the table.',
    eventText: 'After the Shadow player draws a Hunt tile, you may discard "Mithril Coat and Sting" to draw a second tile. Apply the effects of the second tile instead of the first one, then return the first tile to the Hunt Pool.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Blade of Westernesse',
    combatPreCondition: 'Play if a Hobbit is in the battle.',
    combatText: 'Use one hit during the Leader re-roll to eliminate one Minion of your choice, that is participating in the battle.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 6,
    activator: 'Character',
    eventTitle: 'Axe and Bow',
    eventPreCondition: 'Play on the table if Gimli or Legolas are in the Fellowship.',
    eventText: 'After the Shadow player draws a Hunt tile, you may discard "Axe and Bow" to reduce the Hunt damage by one (to a minimum of zero). Any remaining Hunt damage must be confronted normally.',
    eventDiscardCondition: 'You must immediately discard this card from the table if both Gimli and Legolas leave the Fellowship.',
    multiplayerGameInformation: null,
    combatTitle: 'Mighty Attack',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'Before rolling the dice for your Leader re-roll, forfeit the Leadership of one Companion participating in the battle to automatically change on missed die roll to a hit.',
    initiativeNumbers: [4],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 7,
    activator: 'Character',
    eventTitle: 'Horn of Gondor',
    eventPreCondition: 'Play on the table if Boromir is in the Fellowship.',
    eventText: 'After the Shadow player draws a Hunt tile, you may discard "Horn of Gondor" to reduce the Hunt damage by one (to a minimum of zero). Any remaining Hunt damage must be confronted normally.',
    eventDiscardCondition: 'You must immediately discard this card from the table if Boromir leaves the Fellowship.',
    multiplayerGameInformation: null,
    combatTitle: 'Mighty Attack',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'Before rolling the dice for your Leader re-roll, forfeit the Leadership of one Companion participating in the battle to automatically change on missed die roll to a hit.',
    initiativeNumbers: [4],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 8,
    activator: 'Character',
    eventTitle: 'Wizard\'s Staff',
    eventPreCondition: 'Play on the table if Gandalf the Grey is in the Fellowship.',
    eventText: 'You may discard "Wizard\'s Staff" to prevent the Shadow player from drawing a Hunt tile.',
    eventDiscardCondition: 'You must immediately discard this card from the table if Gandalf the Grey leaves the Fellowship.',
    multiplayerGameInformation: null,
    combatTitle: 'Servant of the Secret Fire',
    combatPreCondition: 'Play if Gandalf is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 9,
    activator: 'Character',
    eventTitle: 'Athelas',
    eventPreCondition: null,
    eventText: 'Roll three dice and heal one Corruption point for each die result of 5+.\nIf Strider is the Guide, heal one Corruption point for each die result of 3+ instead.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Andúril',
    combatPreCondition: 'Play if Strider/Aragorn is in the battle.',
    combatText: 'Before rolling the dice for your Leader re-roll, forfeit Strider\'s Leadership to automatically change one missed die roll to a hit, or forfeit Aragorn\'s Leadership to automatically change up to two missed die rolls to hits.',
    initiativeNumbers: [4],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 10,
    activator: 'Character',
    eventTitle: 'There is Another Way',
    eventPreCondition: null,
    eventText: 'Heal one Corruption point.\nThen, if Gollum is the Guide, you may also hide or move the Fellowship (following the normal movement rules).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Heroic Death',
    combatPreCondition: 'Play if a Free Peoples Leader or a Companion is in the battle.',
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, you may eliminate one of your Leaders to cancel one hit, or eliminate one Companion to cancel a number of hits equal to or less than the Companion\'s Level.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 11,
    activator: 'Character',
    eventTitle: 'I Will Go Alone',
    eventPreCondition: 'Play if at least one Companion is in the Fellowship.',
    eventText: 'Separate one Companion or one group of Companions from the Fellowship. You may move the Companions one extra region.\nThen, heal one Corruption point.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Daring Defiance',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'Forfeit the Leadership of all the Companions participating in the battle to cancel the Combat card played by the Shadow player.',
    initiativeNumbers: [0],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 12,
    activator: 'Character',
    eventTitle: 'Bilbo\'s Song',
    eventPreCondition: null,
    eventText: 'Heal one Corruption point.\nIf Gollum is the Guide, heal two Corruption points instead.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Fateful Strike',
    combatPreCondition: 'Play if a Free Peoples Leader or a Companion is in the battle.',
    combatText: 'If your Leader re-roll scores one hit, additionally eliminate a Nazgûl (if in the battle).\nIf the re-roll scores two or more hits, you can eliminate a Minion (if in the battle) instead of a Nazgûl.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 13,
    activator: 'Character',
    eventTitle: 'Mirror of Galadriel',
    eventPreCondition: null,
    eventText: 'Change any one unused Free Peoples Character Action Die result into a Will of the West Die result.\nIf the Fellowship is in Lórien, and Lórien is controlled by the Free Peoples player, also heal one Corruption point.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Heroic Death',
    combatPreCondition: 'Play if a Free Peoples Leader or a Companion is in the battle.',
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, you may eliminate one of your Leaders to cancel one hit, or eliminate one Companion to cancel a number of hits equal to or less than the Companion\'s Level.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 14,
    activator: 'Character',
    eventTitle: 'Challenge of the King',
    eventPreCondition: 'Play if Strider/Aragorn is with a Free Peoples Army in a Gondor or Rohan region.',
    eventText: 'Draw three Hunt tiles. If all three drawn tiles show Eyes, put them back in the Hunt Pool and eliminate Strider/Aragorn.\nOtherwise, discard permanently the drawn tiles bearing an Eye for the remainder of the game.\nAll drawn tiles not bearing an Eye are put back in the Hunt pool.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Sudden Strike',
    combatPreCondition: 'Play if a Free Peoples Leader or Companion is in the battle.',
    combatText: 'Before the Combat roll, roll an additional attack using a number of dice equal to your Leadership (up to a maximum of 5) and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 15,
    activator: 'Character',
    eventTitle: 'Gwaihir the Windlord',
    eventPreCondition: null,
    eventText: 'Separate from the Fellowship, or move, one Companion or one group of Companions as if their Level were 4.\nThis movement of these Companions is allowed to end in a Stronghold under siege.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Daring Defiance',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'Forfeit the Leadership of all the Companions participating in the battle to cancel the Combat card played by the Shadow player.',
    initiativeNumbers: [0],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 16,
    activator: 'Character',
    eventTitle: 'We Prove the Swifter',
    eventPreCondition: null,
    eventText: 'Separate from the Fellowship, or move, one Companion or one group of Companions. You may move them two extra regions.\nThis movement of these Companions is allowed to end in a Stronghold under siege.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Daring Defiance',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'Forfeit the Leadership of all the Companions participating in the battle to cancel the Combat card played by the Shadow player.',
    initiativeNumbers: [0],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 17,
    activator: 'Character',
    eventTitle: 'There and Back Again',
    eventPreCondition: null,
    eventText: 'Separate from the Fellowship one Companion or a group of Companions. You may move them one extra region.\nThen, if Gimli or Legolas are in Dale, Erebor or the Woodland Realm, activate the Dwarven and the North Nations and advance the Dwarven, the Elven and the North Nations one step each on the Political Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Brave Stand',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'The Shadow player rolls one die less in his Combat roll for each Companion in the battle (to a minimum of one).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 18,
    activator: 'Character',
    eventTitle: 'The Eagles are Coming!',
    eventPreCondition: 'Play if a Free Peoples Army containing a Companion is adjacent to, or is in the same region as, a Shadow Army containing a Nazgûl.',
    eventText: 'Roll a die for each Nazgûl present (up to a maximum of five dice) and eliminate a Nazgûl for each roll of 5+.\nAll surviving Nazgûl must immediately be moved to any one Sauron Stronghold controlled by the Shadow player.\nThe Witch-King is not considered a Nazgûl for the purposes of this card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Heroic Death',
    combatPreCondition: 'Play if a Free Peoples Leader or a Companion is in the battle.',
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, you may eliminate one of your Leaders to cancel one hit, or eliminate one Companion to cancel a number of hits equal to or less than the Companion\'s Level.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 19,
    activator: 'Character',
    eventTitle: 'The Ents Awake: Treebeard',
    eventPreCondition: 'Play if Gandalf the White is in play and a Companion is in Fangorn.',
    eventText: 'Roll three dice; for each result of 4+, score one hit against a Shadow Army in Orthanc. If the Army is destroyed, so are any Nazgûl and Minions along with it.\nIf Saruman is in Orthanc without a Shadow Army, eliminate him.\nIf Gandalf the White is in Fangorn or a Rohan region, you may immediately play another Character Event card from your hand without using an Action Die.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Ents\'s Rage',
    combatPreCondition: 'Play if the defending Army is in a Rohan region, Fangorn or Orthanc.',
    combatText: 'Add 2 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 20,
    activator: 'Character',
    eventTitle: 'The Ents Awake: Huorns',
    eventPreCondition: 'Play if Gandalf the White is in play and a Companion is in Fangorn.',
    eventText: 'Roll three dice; for each result of 4+, score one hit against a Shadow Army in Orthanc. If the Army is destroyed, so are any Nazgûl and Minions along with it.\nIf Saruman is in Orthanc without a Shadow Army, eliminate him.\nIf Gandalf the White is in Fangorn or a Rohan region, you may immediately play another Character Event card from your hand without using an Action Die.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Huorn-dark',
    combatPreCondition: 'Play if the defending Army is in a Rohan region, Fangorn or Orthanc.',
    combatText: 'The Shadow player rolls a maximum of two dice in the Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 21,
    activator: 'Character',
    eventTitle: 'The Ents Awake: Entmoot',
    eventPreCondition: 'Play if Gandalf the White is in play and a Companion is in Fangorn.',
    eventText: 'Roll three dice; for each result of 4+, score one hit against a Shadow Army in Orthanc. If the Army is destroyed, so are any Nazgûl and Minions along with it.\nIf Saruman is in Orthanc without a Shadow Army, eliminate him.\nIf Gandalf the White is in Fangorn or a Rohan region, you may immediately play another Character Event card from your hand without using an Action Die.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Nameless Wood',
    combatPreCondition: 'Play if the defending Army is in a Rohan region, Fangorn or Orthanc.',
    combatText: 'If your Combat roll or Leader re-roll score at least one hit, score two additional hits.',
    initiativeNumbers: [5],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 22,
    activator: 'Character',
    eventTitle: 'Dead Men of Dunharrow',
    eventPreCondition: 'Play if Strider/Aragorn is in a Rohan region (including a Stronghold under siege).',
    eventText: 'Move Strider/Aragorn (and any number of Companions in the same region) to Erech, Lamedon or Pelargir.\nIf there is a Shadow Army in that region, roll a die. That Army takes a number of hits equal to the die result and must then retreat. If the Army cannot retreat, it is destroyed. If the Army is destroyed, so are any Nazgûl and Minions along with it.\nYou may then recruit up to three Gondor Regular units in that region, taking control if necessary.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Sudden Strike',
    combatPreCondition: 'Play if a Free Peoples Leader or Companion is in the battle.',
    combatText: 'Before the Combat roll, roll an additional attack using a number of dice equal to your Leadership (up to a maximum of 5) and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 23,
    activator: 'Character',
    eventTitle: 'House of the Stewards',
    eventPreCondition: 'Play if Boromir is in a Gondor region.',
    eventText: 'Recruit one Gondor unit (Regular or Elite) in the region with Boromir.\nThen, draw two Strategy Event cards.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Brave Stand',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'The Shadow player rolls one die less in his Combat roll for each Companion in the battle (to a minimum of one).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Character',
    number: 24,
    activator: 'Character',
    eventTitle: 'The Grey Company',
    eventPreCondition: 'Play if Strider/Aragorn is with a Free Peoples Army.',
    eventText: 'Eliminate one Regular unit to recruit one Elite unit of the same Nation, in the Army with Strider/Aragorn.\nThen, draw two Strategy Event cards.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Brave Stand',
    combatPreCondition: 'Play if a Companion is in the battle.',
    combatText: 'The Shadow player rolls one die less in his Combat roll for each Companion in the battle (to a minimum of one).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 1,
    activator: 'Army',
    eventTitle: 'The Last Battle',
    eventPreCondition: 'Play on the table if Aragorn is with a Free Peoples Army in a region outside of a Free Peoples Nation.',
    eventText: 'While this card is in play, Action Dice used to move the Fellowship are not added to the Hunt Box.',
    eventDiscardCondition: 'You must discard this card from the table as soon as the Fellowship is declared or revealed.',
    multiplayerGameInformation: null,
    combatTitle: 'Daylight',
    combatPreCondition: null,
    combatText: 'The Shadow player rolls a maximum of three dice during his Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 2,
    activator: 'Army',
    eventTitle: 'A Power too Great',
    eventPreCondition: 'Play on the table.',
    eventText: 'Advance the Elven Nation one step on the Political Track.\nWhile this card is in play, the Shadow player cannot move an Army into or attack (either in normal battle or in a siege) Lórien, Rivendell or the Grey Havens.',
    eventDiscardCondition: 'The Shadow player can force "A Power too Great" to be discarded by using any one Action Die and discarding one Army Event card and one Character Event card from his hand.',
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'No Quarter',
    combatPreCondition: null,
    combatText: 'If your Combat roll or Leader re-roll scores at least one hit, score one additional hit.',
    initiativeNumbers: [5],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 3,
    activator: 'Army',
    eventTitle: 'The Power of Tom Bombadil',
    eventPreCondition: 'Play on the table.',
    eventText: 'Advance The North Nation one step on the Political Track.\nWhile this card is in play, the Shadow player cannot move an Army into or attack The Old Forest, The Shire or Buckland.',
    eventDiscardCondition: 'The Shadow player can force "The Power of Tom Bombadil" to be discarded by using any one Action Die and discarding one Army Event card and one Character Event card from his hand.',
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Advantageous Position',
    combatPreCondition: 'Play if the defending Army is inside the borders of a Free Peoples Nation.',
    combatText: 'Subtract 1 from all dice on the Combat roll of the Shadow player (an unmodified \'6\' isstill considered a hit for him).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 4,
    activator: 'Muster',
    eventTitle: 'Book of Mazarbul',
    eventPreCondition: null,
    eventText: 'Move any or all Companions who are not in the Fellowship.\nThen, if a Companion is in Erebor or Ered Luin, activate the Dwarven Nation and move it directly to the "At War" step.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Advantageous Position',
    combatPreCondition: 'Play if the defending Army is inside the borders of a Free Peoples Nation.',
    combatText: 'Subtract 1 from all dice on the Combat roll of the Shadow player (an unmodified \'6\' isstill considered a hit for him).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 5,
    activator: 'Army',
    eventTitle: 'The Spirit of Mordor',
    eventPreCondition: null,
    eventText: 'Choose a Shadow Army anywhere on the board that is composed of Army units from at least two different Shadow Nations.\nRoll five dice and score one hit against this Army for each result of 5+.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Scouts',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, retreat your Army to an adjacent free region or withdraw into a siege.',
    initiativeNumbers: [1],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 6,
    activator: 'Army',
    eventTitle: 'Faramir\'s Rangers',
    eventPreCondition: null,
    eventText: 'Choose a Shadow Army in Osgiliath or South Ithilien or North Ithilien.\nRoll three dice and score one hit against this Army for each result of 5+.\nThen, if there is a Free Peoples Army in Osgiliath, recruit one Gondor unit (Regular or Elite) and one Gondor Leader there.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Shield-wall',
    combatPreCondition: null,
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, if your opponent scored two or more hits, cancel one hit.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 7,
    activator: 'Muster',
    eventTitle: 'Fear! Fire! Foes!',
    eventPreCondition: null,
    eventText: 'Move any or all Companions who are not in the Fellowship.\nThen, if a Companion is in The Shire or Bree, activate the North Nation and move it directly to the "At War" step.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Shield-wall',
    combatPreCondition: null,
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, if your opponent scored two or more hits, cancel one hit.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 8,
    activator: 'Muster',
    eventTitle: 'Wisdom of Elrond',
    eventPreCondition: null,
    eventText: 'Activate one Free Peoples Nation of your choice and advance that Nation one step on the Political Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Confusion',
    combatPreCondition: null,
    combatText: 'Every unmodified die result of \'1\' in the Shadow player\'s Combat roll scores one hit against the Shadow Army.\nAny such result cannot be rolled again during the Shadow player\'s Leader re-roll.',
    initiativeNumbers: [4],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 9,
    activator: 'Muster',
    eventTitle: 'The Red Arrow',
    eventPreCondition: 'Play if the Gondor Nation is active.',
    eventText: 'Advance the Rohan Nation one step on the Political Track.\nThen, recruit one Rohan unit (Regular or Elite) and one Rohan Leader in Edoras.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Scouts',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, retreat your Army to an adjacent free region or withdraw into a siege.',
    initiativeNumbers: [1],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 10,
    activator: 'Army',
    eventTitle: 'Help Unlooked For',
    eventPreCondition: null,
    eventText: 'Attack a Shadow Army besieging a Stronghold with a Free Peoples Army in an adjacent region.\nFor this entire battle, the Shadow player rolls one die less during the Combat roll for each Free Peoples unit in the besieged Stronghold (to a minimum of one).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'No Quarter',
    combatPreCondition: null,
    combatText: 'If your Combat roll or Leader re-roll scores at least one hit, score one additional hit.',
    initiativeNumbers: [5],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 11,
    activator: 'Army',
    eventTitle: 'Path of the Woses',
    eventPreCondition: 'Play if the Rohan Nation is "At War".',
    eventText: 'Move a Free Peoples Army from any one Rohan region (including a Stronghold under siege) directly to Minas Tirith.\nIf Minas Tirith is under siege or is controlled by the Shadow player, move the Army to a region adjacent to Minas Tirith instead. The destination region must be free for the purposes of army movement.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Sudden Strike',
    combatPreCondition: 'Play if a Free Peoples Leader or Companion is in the battle.',
    combatText: 'Before the Combat roll, roll an additional attack using a number of dice equal to your Leadership (up to a maximum of 5) and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 12,
    activator: 'Army',
    eventTitle: 'Through a Day and a Night',
    eventPreCondition: 'Play on a Free Peoples Army containing a Companion.',
    eventText: 'Move the Army containing the Companion(s) up to two regions. The regions must be free for the purposes of Army movement, and no Free Peoples units may be picked up or dropped off along the way (other than, possibly, splitting the Army initially).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Confusion',
    combatPreCondition: null,
    combatText: 'Every unmodified die result of \'1\' in the Shadow player\'s Combat roll scores one hit against the Shadow Army.\nAny such result cannot be rolled again during the Shadow player\'s Leader re-roll.',
    initiativeNumbers: [4],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 13,
    activator: 'Muster',
    eventTitle: 'Círdan\'s Ships',
    eventPreCondition: 'Play if the Elves are "At War".',
    eventText: 'Recruit two Elven units (Regular or Elite) in a coastal region containing a Free Peoples Army.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Charge',
    combatPreCondition: 'Play if a Free Peoples Elite unit is in the battle.',
    combatText: 'Before the Combat roll, roll an additional attack using only the Free Peoples Elite units (up to a maximum of 5) and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 14,
    activator: 'Muster',
    eventTitle: 'Guards of the Citadel',
    eventPreCondition: null,
    eventText: 'Recruit one Gondor unit (Regular or Elite) and one Gondor Leader in Minas Tirith.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Charge',
    combatPreCondition: 'Play if a Free Peoples Elite unit is in the battle.',
    combatText: 'Before the Combat roll, roll an additional attack using only the Free Peoples Elite units (up to a maximum of 5) and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 15,
    activator: 'Muster',
    eventTitle: 'Celeborn\'s Galadhrim',
    eventPreCondition: null,
    eventText: 'Recruit one Elven unit (Regular or Elite) in Lórien.\nThen, draw one Strategy Event card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Daylight',
    combatPreCondition: null,
    combatText: 'The Shadow player rolls a maximum of three dice during his Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 16,
    activator: 'Muster',
    eventTitle: 'Riders of Théoden',
    eventPreCondition: null,
    eventText: 'Recruit one Rohan unit (Regular or Elite) and one Rohan Leader in either Edoras or in a Rohan region containing a Companion.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Daylight',
    combatPreCondition: null,
    combatText: 'The Shadow player rolls a maximum of three dice during his Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 17,
    activator: 'Muster',
    eventTitle: 'Grimbeorn the Old, Son of Beorn',
    eventPreCondition: null,
    eventText: 'Recruit one North unit (Regular or Elite) and one North Leader in Carrock.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Scouts',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, retreat your Army to an adjacent free region or withdraw into a siege.',
    initiativeNumbers: [1],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 18,
    activator: 'Muster',
    eventTitle: 'Imrahil of Dol Amroth',
    eventPreCondition: null,
    eventText: 'Recruit one Gondor unit (Regular or Elite) and one Gondor Leader in Dol Amroth.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Shield-wall',
    combatPreCondition: null,
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, if your opponent scored two or more hits, cancel one hit.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 19,
    activator: 'Muster',
    eventTitle: 'King Brand\'s Men',
    eventPreCondition: null,
    eventText: 'Recruit two North Regular units in Dale.\nThen, draw one Strategy Event card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Shield-wall',
    combatPreCondition: null,
    combatText: 'Before you remove casualties inflicted by your opponent\'s Combat roll and Leader re-roll, if your opponent scored two or more hits, cancel one hit.',
    initiativeNumbers: [6],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 20,
    activator: 'Muser',
    eventTitle: 'Swords in Eriador',
    eventPreCondition: null,
    eventText: 'Recruit one North unit (Regular or Elite) in The Shire and one Dwarven unit (Regular or Elite) in Ered Luin.\nThen, draw one Strategy Event card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Advantageous Position',
    combatPreCondition: 'Play if the defending Army is inside the borders of a Free Peoples Nation.',
    combatText: 'Subtract 1 from all dice on the Combat roll of the Shadow player (an unmodified \'6\' isstill considered a hit for him).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 21,
    activator: 'Muster',
    eventTitle: 'Kindred of Glorfindel',
    eventPreCondition: null,
    eventText: 'Recruit one Elven unit (Regular or Elite) in Rivendell.\nThen, draw one Strategy Event card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Advantageous Position',
    combatPreCondition: 'Play if the defending Army is inside the borders of a Free Peoples Nation.',
    combatText: 'Subtract 1 from all dice on the Combat roll of the Shadow player (an unmodified \'6\' isstill considered a hit for him).',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 22,
    activator: 'Muster',
    eventTitle: 'Dain Ironfoot\'s Guard',
    eventPreCondition: null,
    eventText: 'Recruit one Dwarven unit (Regular or Elite) and one Dwarven Leader in Erebor.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Valour',
    combatPreCondition: 'Play if a Free Peoples Elite unit is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 23,
    activator: 'Muster',
    eventTitle: 'Éomer, Son of Éomund',
    eventPreCondition: null,
    eventText: 'Recruit one Rohan unit (Regular or Elite) and one Rohan Leader in a free Rohan region containing a Settlement.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Rohan',
    combatTitle: 'Valour',
    combatPreCondition: 'Play if a Free Peoples Elite unit is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Free Peoples',
    type: 'Strategy',
    number: 24,
    activator: 'Muster',
    eventTitle: 'Thranduil\'s Archers',
    eventPreCondition: null,
    eventText: 'Recruit one Elven unit (Regular or Elite) in Woodland Realm.\nThen, draw one Strategy Event card.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Gondor',
    combatTitle: 'Valour',
    combatPreCondition: 'Play if a Free Peoples Elite unit is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 1,
    activator: 'Character',
    eventTitle: 'Shelob\'s Lair',
    eventPreCondition: null,
    eventText: 'The "Shelob\'s Lair" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'One for the Dark Lord',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 2,
    activator: 'Character',
    eventTitle: 'The Ring is Mine',
    eventPreCondition: null,
    eventText: 'The "The Ring is Mine" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'One for the Dark Lord',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 3,
    activator: 'Character',
    eventTitle: 'On, On They Went',
    eventPreCondition: null,
    eventText: 'The "On, On They Went" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'One for the Dark Lord',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 4,
    activator: 'Character',
    eventTitle: 'Give it to Uss!',
    eventPreCondition: null,
    eventText: 'The "Give it to Uss!" special Hunt tile is now in play.\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'One for the Dark Lord',
    combatPreCondition: 'Play if the defending Army is in the same region as the Fellowship.',
    combatText: 'Add 1 to all dice on your Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 5,
    activator: 'Character',
    eventTitle: 'Orc Patrol',
    eventPreCondition: 'Play if the Fellowship is not in a region containing a Free Peoples Settlement.',
    eventText: 'Draw a Hunt tile.\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\nOtherwise, follow the rules for a successful Hunt.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Cruel as Death',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 2 or more.',
    combatText: 'Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 6,
    activator: 'Character',
    eventTitle: 'Isildur\'s Bane',
    eventPreCondition: 'Play if the Fellowship is not in a region containing a Free Peoples Settlement.',
    eventText: 'Draw a Hunt tile.\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\nOtherwise, follow the rules for a successful Hunt, except that Hunt Damage may not be reduced in any way before using the Ring.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Cruel as Death',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 2 or more.',
    combatText: 'Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 7,
    activator: 'Character',
    eventTitle: 'Foul Thing from the Deep',
    eventPreCondition: 'Play if the Fellowship is not in a region containing a Free Peoples Settlement.',
    eventText: 'Draw a Hunt tile.\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\nOtherwise, follow the rules for a successful Hunt, except that the Free Peoples player must reduce Hunt Damage (if any) by eliminating a random Companion (unless there are no Companions in the Fellowship) before using the Ring.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'They are Terrible',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.',
    initiativeNumbers: [4],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 8,
    activator: 'Character',
    eventTitle: 'Candles of Corpses',
    eventPreCondition: 'Play if the Fellowship is not in a region containing a Free Peoples Settlement.',
    eventText: 'Roll three dice and add one Corruption point on each result of 4+.\nIf Gollum is the Guide, add one Corruption point on each result of "6" instead.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Dread and Despair',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 9,
    activator: 'Character',
    eventTitle: 'Nazgûl Search',
    eventPreCondition: 'Play if the Fellowship is on step 1 or higher on the Fellowship Track.',
    eventText: 'Move any or all of the Nazgûl.\nThen, if at least one Nazgûl is in the region with the Fellowship, the Fellowship is revealed.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Foul Stench',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 10,
    activator: 'Character',
    eventTitle: 'Cruel Weather',
    eventPreCondition: 'Play if the Fellowship is on step 1 or higher on the Fellowship Track.',
    eventText: 'Move the Fellowship to an adjacent region.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Cruel as Death',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 2 or more.',
    combatText: 'Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 11,
    activator: 'Character',
    eventTitle: 'The Nazgûl Strike!',
    eventPreCondition: 'Play if the Fellowship is on step 1 or higher on the Fellowship Track.',
    eventText: 'Move any or all of the Nazgûl.\nThen, if at least one Nazgûl is in the region with the Fellowship, you may either discard one Free Peoples Character Event card from the table or roll for the Hunt (as if the Free Peoples player had moved the Fellowship).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Black Breath',
    combatPreCondition: 'Play if a Nazgûl is in the battle.',
    combatText: 'If your Leader re-roll scores at least one hit, you may additionally eliminate one Free Peoples Leader participating in the battle. Alternatively, you can choose to eliminate a Companion in the battle, if the number of hits equals or exceeds the Companion\'s Level.',
    initiativeNumbers: [6],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 12,
    activator: 'Character',
    eventTitle: 'Morgul Wound',
    eventPreCondition: 'Play if the Fellowship is revealed.',
    eventText: 'If the Fellowship\'s current Corruption is three or less, add two Corruption points, otherwise add one Corruption point.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Black Breath',
    combatPreCondition: 'Play if a Nazgûl is in the battle.',
    combatText: 'If your Leader re-roll scores at least one hit, you may additionally eliminate one Free Peoples Leader participating in the battle. Alternatively, you can choose to eliminate a Companion in the battle, if the number of hits equals or exceeds the Companion\'s Level.',
    initiativeNumbers: [6],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 13,
    activator: 'Character',
    eventTitle: 'Lure of the Ring',
    eventPreCondition: 'Play if the Fellowship is revealed.',
    eventText: 'Randomly select one Companion in the Fellowship by drawing a Companion counter.\nThe Free Peoples player must choose either to add Corruption equal to the Companion\'s Level or to eliminate him.\nIf Gollum is the Guide, add one Corruption point instead.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'They are Terrible',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.',
    initiativeNumbers: [4],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 14,
    activator: 'Character',
    eventTitle: 'The Breaking of the Fellowship',
    eventPreCondition: 'Play if the Fellowship is revealed.',
    eventText: 'Draw a Hunt tile.\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\nOtherwise, the Free Peoples player must separate a number of Companions equal to the number on the tile (if possible), placing them in the same region as the Fellowship.\nIgnore any "Reveal" or "Stop" icons on the tile.\nIf Gollum is the Guide, add one Corruption point instead.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Dread and Despair',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 15,
    activator: 'Character',
    eventTitle: 'Worn with Sorrow and Toil',
    eventPreCondition: 'Play on the table.',
    eventText: 'When "Worn with Sorrow and Toil" is in play, if a Companion in the Fellowship is taken as a casualty you may also discard one of the Free Peoples player\'s Character Event cards from his hand (choosing it randomly) or from the table.',
    eventDiscardCondition: 'You must discard this card from the table immediately if the Fellowship is declared in a Free Peoples City or Stronghold controlled by the Free Peoples player.',
    multiplayerGameInformation: null,
    combatTitle: 'Words of Power',
    combatPreCondition: 'Play if a Nazgûl is in the battle.',
    combatText: 'Choose a Companion. That Companion\'s Leadership and special abilities are cancelled for this Combat round.',
    initiativeNumbers: [1],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 16,
    activator: 'Character',
    eventTitle: 'Flocks of Crebain',
    eventPreCondition: 'Play on the table.',
    eventText: 'Before you make a Hunt roll, you may discard "Flocks of Crebain" to add 1 to all dice on that Hunt roll (including re-rolls).',
    eventDiscardCondition: 'You must discard this card from the table immediately if the Fellowship is declared in a Free Peoples City or Stronghold controlled by the Free Peoples player.',
    multiplayerGameInformation: null,
    combatTitle: 'They are Terrible',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.',
    initiativeNumbers: [4],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 17,
    activator: 'Character',
    eventTitle: 'Balrog of Moria',
    eventPreCondition: 'Play on the table.',
    eventText: 'You may discard "Balrog of Moria" to draw an additional Hunt tile if the Fellowship moves into, out of, or through Moria while being declared or revealed. If the tile shows an Eye, discard it without effect; otherwise follow the rules for a successful Hunt.\nIgnore any "Reveal" icon on the drawn tile if the Fellowship has been declared in a Free Peoples City or Stronghold.',
    eventDiscardCondition: 'Or, you may discard "Balrog of Moria" to use its Combat card effect as if you were playing the card from your hand.',
    multiplayerGameInformation: null,
    combatTitle: 'Durin\'s Bane',
    combatPreCondition: 'Play if the defending Army is within two regions of Moria.',
    combatText: 'Before the Combat Roll, roll an additional attack using three Combat dice; score hits on 4+ and apply the result immediately.',
    initiativeNumbers: [2],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 18,
    activator: 'Character',
    eventTitle: 'The Lidless Eye',
    eventPreCondition: null,
    eventText: 'Change up to three unused Shadow Action Dice results into "Eye" results.\nPlace these dice in the Hunt Box immediately.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Words of Power',
    combatPreCondition: 'Play if a Nazgûl is in the battle.',
    combatText: 'Choose a Companion. That Companion\'s Leadership and special abilities are cancelled for this Combat round.',
    initiativeNumbers: [1],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 19,
    activator: 'Character',
    eventTitle: 'Dreadful Spells',
    eventPreCondition: 'Play if a Shadow Army containing Nazgûl is adjacent to, or is in the same region as, a Free Peoples Army.',
    eventText: 'Roll a number of dice equal to the number of Nazgûl (up to a maximum of 5) and score one hit for every result of 5+.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Devilry of Orthanc',
    combatPreCondition: 'Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 20,
    activator: 'Character',
    eventTitle: 'Grond, Hammer of the Underworld',
    eventPreCondition: 'Play if the Witch-King is in play and is with a Shadow Army besieging a Stronghold.',
    eventText: 'Attack that Stronghold. The siege lasts for three Combat rounds instead of one. During the first round, the Free Peoples player cannot use a Combat card unless a Companion is in the battle.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Dread and Despair',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 21,
    activator: 'Character',
    eventTitle: 'The Palantír of Orthanc',
    eventPreCondition: 'Play on the table if Saruman is in play.',
    eventText: 'When "The Palantír of Orthanc" is in play, after you use an Event Action Die result to play an Event card, immediately draw another card from either one of your decks.',
    eventDiscardCondition: 'The Free Peoples player can force "The Palantír of Orthanc" to be discarded by either using a Will of the West Action Die result, or using any Action Die and one Elven Ring. You must discard this card if Saruman is eliminated.',
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Cruel as Death',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 2 or more.',
    combatText: 'Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 22,
    activator: 'Character',
    eventTitle: 'Wormtongue',
    eventPreCondition: 'Play on the table if Saruman is in play.',
    eventText: 'When "Wormtongue" is in play, Rohan cannot be activated except by an appropriate Companion, or by the Fellowship being declared in Edoras or Helm\'s Deep, or by an attack on Edoras or Helm\'s Deep.',
    eventDiscardCondition: 'You must discard this card from the table as soon as Rohan is activated, or if Saruman is eliminated.',
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Foul Stench',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 23,
    activator: 'Character',
    eventTitle: 'The Ringwraiths Are Abroad',
    eventPreCondition: null,
    eventText: 'Move any or all of the Nazgûl.\nThen, you may either move two Armies each containing a Nazgûl, or attack with one Army containing a Nazgûl.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Words of Power',
    combatPreCondition: 'Play if a Nazgûl is in the battle.',
    combatText: 'Choose a Companion. That Companion\'s Leadership and special abilities are cancelled for this Combat round.',
    initiativeNumbers: [1],
  },
  {
    side: 'Shadow',
    type: 'Character',
    number: 24,
    activator: 'Character',
    eventTitle: 'The Black Captain Commands',
    eventPreCondition: 'Play if the Witch-king is in play.',
    eventText: 'You may either recruit two Nazgûl in the region containing the Witch-king, or move any or all of the Nazgûl.\nThen, you may move or attack with an Army containing the Witch-king.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Foul Stench',
    combatPreCondition: 'Play if the total Nazgûl Leadership is 1 or more.',
    combatText: 'If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 1,
    activator: 'Army',
    eventTitle: 'Return to Valinor',
    eventPreCondition: 'Play if you control at least one Elven Stronghold.',
    eventText: 'For each region with an Elven Stronghold which is not under siege, roll a number of dice equal to the Elven Army units in that region (up to a maximum of 5) and score one hit against that army for each result of "6".',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Deadly Strife',
    combatPreCondition: null,
    combatText: 'Both Armies add 2 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 2,
    activator: 'Army',
    eventTitle: 'The Fighting Uruk-hai',
    eventPreCondition: 'Play if Saruman is in play, and if an Army containing an Isengard unit is besieging a Stronghold.',
    eventText: 'Attack that Stronghold. The siege lasts for three Combat rounds instead of one. During the first round, the Free Peoples player cannot use a Combat card unless a Companion is in the battle.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Onslaught',
    combatPreCondition: null,
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 3,
    activator: 'Army',
    eventTitle: 'Denethor\'s Folly',
    eventPreCondition: 'Play on the table if Minas Tirith is under siege by a Shadow Army.',
    eventText: 'When you play this card, immediately eliminate one Free Peoples Leader in Minas Tirith.\nWhen "Denethor\'s Folly" is in play, the Free Peoples player cannot use Combat cards for battles fought in Minas Tirith.',
    eventDiscardCondition: 'The Free Peoples player can force "Denethor\'s Folly" to be discarded using a Will of the West Action Die result, or any Action Die if Gandalf or Aragorn is in Minas Tirith.',
    multiplayerGameInformation: null,
    combatTitle: 'Devilry of Orthanc',
    combatPreCondition: 'Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 4,
    activator: 'Army',
    eventTitle: 'The Day Without Dawn',
    eventPreCondition: 'Play if all Shadow Nations are "At War".',
    eventText: 'Discard all unused Free Peoples Action Dice that show a Will of the West result.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Relentless Assault',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 5,
    activator: 'Muster',
    eventTitle: 'Threats and Promises',
    eventPreCondition: 'Play on the table.',
    eventText: 'When "Threats and Promises" is in play, the Free Peoples player cannot advance a passive Nation on the Political Track using a Muster Action Die.',
    eventDiscardCondition: 'You must discard this card from the table as soon as a Free Peoples Nation advances on the Political Track either due to an attack or due to a Companion\'s special ability.',
    multiplayerGameInformation: null,
    combatTitle: 'Devilry of Orthanc',
    combatPreCondition: 'Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.',
    combatText: 'Add 1 to all dice on your Combat roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 6,
    activator: 'Muster',
    eventTitle: 'Stormcrow',
    eventPreCondition: 'Play if either the Fellowship or a Companion is inside the borders of a Free Peoples Nation not "At War."',
    eventText: 'Move that Nation\'s Political Counter back one step on the Political Track.\nThen, the Free Peoples player must eliminate one Leader or Army unit of that Nation (Regular or Elite).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Great Host',
    combatPreCondition: null,
    combatText: 'If, after removing casualties from the Combat roll and Leader re-roll your Army units are at least twice as many as the enemy Army units, score one automatic hit.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 7,
    activator: 'Army',
    eventTitle: 'Shadows Gather',
    eventPreCondition: null,
    eventText: 'Move one Shadow Army up to three regions. The movement must end in a region already occupied by another Shadow Army (that must not be under siege). The regions must be free for the purposes of Army movement, and no Shadow units may be picked up or dropped off along the way (other than, possibly, splitting the Army initially).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Mûmakil',
    combatPreCondition: 'Play if a Southrons & Easterlings Elite unit is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll. If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-Combat attack from a Combat card), score one additional hit.',
    initiativeNumbers: [3, 5],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 8,
    activator: 'Army',
    eventTitle: 'The Shadow Lengthens',
    eventPreCondition: null,
    eventText: 'Move two Shadow Armies up to two regions. Each movement must end in a region already occupied by another Shadow Army (that must not be under siege). The regions must be free for the purposes of Army movement, and no Shadow units may be picked up or dropped off along the way (other than, possibly, splitting the Army initially).',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Mûmakil',
    combatPreCondition: 'Play if a Southrons & Easterlings Elite unit is in the battle.',
    combatText: 'Add 1 to all dice on your Combat roll. If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-Combat attack from a Combat card), score one additional hit.',
    initiativeNumbers: [3, 5],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 9,
    activator: 'Army',
    eventTitle: 'The Shadow is Moving',
    eventPreCondition: 'Play if all Shadow Nations are "At War".',
    eventText: 'Move up to four different Shadow Armies one region each.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Swarm of Bats',
    combatPreCondition: null,
    combatText: 'Cancel the effects of the Combat card played by the Free Peoples player.\nIf the Free Peoples player did not play a card, add 1 to all dice on your Leader re-roll.',
    initiativeNumbers: [0],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 10,
    activator: 'Army',
    eventTitle: 'Corsairs of Umbar',
    eventPreCondition: 'Play if the Southrons & Easterlings are "At War".',
    eventText: 'Move one Shadow Army from Umbar to a Gondor coastal region.\nIf there is a Free Peoples Army in the region, a battle starts. The attacking Shadow Army cannot cease the attack, unless the Free Peoples Army was already under siege.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Deadly Strife',
    combatPreCondition: null,
    combatText: 'Both Armies add 2 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 11,
    activator: 'Muster',
    eventTitle: 'Rage of the Dunlendings',
    eventPreCondition: 'Play if Isengard is "At War".',
    eventText: 'Recruit two Isengard Regular units in a free region adjacent to North or South Dunland.\nYou may also move to this region up to four Isengard units (Regular or Elite) from North Dunland and/or South Dunland.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Relentless Assault',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 12,
    activator: 'Muster',
    eventTitle: 'Return of the Witch-king',
    eventPreCondition: 'Play if the Witch-king is in play.',
    eventText: 'Move the Witch-king to Angmar and recruit two Sauron Regular units and one Sauron Elite unit there.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Swarm of Bats',
    combatPreCondition: null,
    combatText: 'Cancel the effects of the Combat card played by the Free Peoples player.\nIf the Free Peoples player did not play a card, add 1 to all dice on your Leader re-roll.',
    initiativeNumbers: [0],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 13,
    activator: 'Army',
    eventTitle: 'Half-orcs and Goblin-men',
    eventPreCondition: 'Play if Isengard is "At War".',
    eventText: 'Recruit one Isengard unit (Regular or Elite) in a region where a Shadow Army is present.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'We Come to Kill',
    combatPreCondition: 'Play if a Shadow Elite unit is in the battle.',
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 14,
    activator: 'Army',
    eventTitle: 'Olog-hai',
    eventPreCondition: 'Play if Sauron is "At War".',
    eventText: 'Recruit one Sauron unit (Regular or Elite) in a region where a Shadow Army is present.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'We Come to Kill',
    combatPreCondition: 'Play if a Shadow Elite unit is in the battle.',
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 15,
    activator: 'Army',
    eventTitle: 'Hill-trolls',
    eventPreCondition: 'Play if Sauron is "At War".',
    eventText: 'Replace two Sauron Regular units anywhere on the game board with two Sauron Elite units.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'We Come to Kill',
    combatPreCondition: 'Play if a Shadow Elite unit is in the battle.',
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 16,
    activator: 'Muster',
    eventTitle: 'A New Power is Rising',
    eventPreCondition: 'Play if Saruman is in play.',
    eventText: 'Recruit two Isengard Regular units in each of North and South Dunland and two Isengard units (Regular or Elite) in Orthanc.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Great Host',
    combatPreCondition: null,
    combatText: 'If, after removing casualties from the Combat roll and Leader re-roll your Army units are at least twice as many as the enemy Army units, score one automatic hit.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 17,
    activator: 'Muster',
    eventTitle: 'Many Kings to the Service of Mordor',
    eventPreCondition: null,
    eventText: 'Recruit two Southron & Easterling Regular units in each of three different Southron & Easterlings Settlements.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Great Host',
    combatPreCondition: null,
    combatText: 'If, after removing casualties from the Combat roll and Leader re-roll your Army units are at least twice as many as the enemy Army units, score one automatic hit.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 18,
    activator: 'Muster',
    eventTitle: 'The King is Revealed',
    eventPreCondition: 'Play if Aragorn is in play.',
    eventText: 'Recruit five Sauron Regular units and a Nazgûl in Minas Morgul.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Relentless Assault',
    combatPreCondition: null,
    combatText: 'Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 19,
    activator: 'Muster',
    eventTitle: 'Shadow on the Misty Mountains',
    eventPreCondition: null,
    eventText: 'Recruit two Sauron units (Regular or Elite) and one Nazgûl in either Mount Gram or Moria.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Onslaught',
    combatPreCondition: null,
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 20,
    activator: 'Muster',
    eventTitle: 'Orcs Multiplying Again',
    eventPreCondition: null,
    eventText: 'Recruit three Sauron Regular units in Dol Guldur and three Sauron Regular units in Mount Gundabad.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Onslaught',
    combatPreCondition: null,
    combatText: 'After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.',
    initiativeNumbers: [7],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 21,
    activator: 'Muster',
    eventTitle: 'Horde From the East',
    eventPreCondition: 'Play if the Southron & Easterling are "At War".',
    eventText: 'Recruit five Southron & Easterling Regular units in a free region inside the Southron and Easterling Nation. This region must be adjacent to the eastern edge of the map.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'Saruman and Sauron Allies',
    combatTitle: 'Deadly Strife',
    combatPreCondition: null,
    combatText: 'Both Armies add 2 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 22,
    activator: 'Muster',
    eventTitle: 'Monsters Roused',
    eventPreCondition: null,
    eventText: 'Recruit one Sauron Regular unit in each of Angmar, Ettenmoors and Weather Hills, and one Sauron Elite unit in Trollshaws.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Desperate Battle',
    combatPreCondition: null,
    combatText: 'Both Armies add 1 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 23,
    activator: 'Muster',
    eventTitle: 'Musterlings of Long-planned War',
    eventPreCondition: 'Play if all Shadow Nations are "At War".',
    eventText: 'Recruit five Southron & Easterling Regular units in Gorgoroth and five Sauron Regular units in Nurn.',
    eventDiscardCondition: null,
    multiplayerGameInformation: null,
    combatTitle: 'Desperate Battle',
    combatPreCondition: null,
    combatText: 'Both Armies add 1 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
  {
    side: 'Shadow',
    type: 'Strategy',
    number: 24,
    activator: 'Muster',
    eventTitle: 'Pits of Mordor',
    eventPreCondition: 'Play if Sauron is "At War".',
    eventText: 'Recruit two Sauron Regular units in each of three different Sauron Strongholds.',
    eventDiscardCondition: null,
    multiplayerGameInformation: 'The Witch-king',
    combatTitle: 'Desperate Battle',
    combatPreCondition: null,
    combatText: 'Both Armies add 1 to all dice on their Combat roll and Leader re-roll.',
    initiativeNumbers: [3],
  },
];